name: tele_models
description: Data models for TeleDeck
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  tele_constants:
    path: ../tele_constants

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
