name: tele_logging
description: Crash logging service for TeleDeck
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  path_provider: any

  # Internal packages
  tele_models: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
