name: {{package_prefix.snakeCase()}}_{{name.snakeCase()}}
description: {{description}}
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
{{#support_android}}
      android:
        package: com.{{package_prefix.snakeCase()}}.{{name.snakeCase()}}
        pluginClass: {{name.pascalCase()}}Plugin
{{/support_android}}
{{#support_ios}}
      ios:
        pluginClass: {{name.pascalCase()}}Plugin
{{/support_ios}}
{{#support_linux}}
      linux:
        pluginClass: {{name.pascalCase()}}Plugin
{{/support_linux}}
{{#support_macos}}
      macos:
        pluginClass: {{name.pascalCase()}}Plugin
{{/support_macos}}
{{#support_windows}}
      windows:
        pluginClass: {{name.pascalCase()}}PluginCApi
{{/support_windows}}
{{#support_web}}
      web:
        pluginClass: {{name.pascalCase()}}Web
        fileName: {{name.snakeCase()}}_web.dart
{{/support_web}}
